---
title: "Untitled"
author: "Ivan Stankevich"
date: "2023-11-09"
output: html_document
---

```{r setup, include=FALSE}

library(forecast)
library(tseries)
library(openxlsx)
library(ggplot2)
library(quantmod)
library(rusquant)
library(HARModel)
library(midasr)
library(lubridate)

knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

А ещё мы можем писать формулы техом!

> А тут анекдот!

\[ RV = \sum_{i = 1}^N r_{i,t}^2  \]


```{r cars}


intradayData = getSymbols.Moex('SBER', period = "5min", from = "2020-01-01")

str(intradayData)

intradayData$date <- as.Date(format(intradayData$timestamp, format = "%d-%m-%Y"), 
                             format = "%d-%m-%Y")


dailyDF <- data.frame(date = unique(intradayData$date), 
                      RV = 0, 
                      RQ = 0)

for (i in 1:nrow(dailyDF)){
  thisDate <- dailyDF$date[i]
  tmp <- intradayData[intradayData$date == thisDate, ]
  r <- diff(log(tmp$close))
  
  dailyDF$RV[i] <- sum(r^2)
  dailyDF$RQ[i] <- sum(r^4)
}


plot(ts(dailyDF$RV), ylim = c(0, 0.01))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

plot(ts(dailyDF$RQ), ylim = c(0, 0.000001))

```


