name: Build Report
on:   
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: report/
          root_file: document.tex
          latexmk_shell_escape: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Article
          path: report/document.pdf
